### PR TITLE
Fixes for issue #44 - TokenResponse/Refresh & Associated code cleanup

### LINKED ISSUE #44: Authenticate Endpoint Should Return User Object and Token Should Be Refreshable
```
As a: frontend developer
I want to: get a user object back when I do `POST /authenticate`
So that: I know who the user who logged in is
```

Currently, there is no way of working out who logged in. To fix this, we should return a copy of the User object in the response so that we have their id, alias etc.

```js
{
  token: String,
  user: Object
}
```

Authentication tokens also currently expire after 10 minutes, therefore we should have another endpoint to refresh these tokens.

### PR DESCRIPTION
**Pull request by AtrumAmantus**
Resolves #44 
- Update TokenResponse model (UserProfile & token)
  - Update Authenticate endpoint
  - Update UserRegistration endpoint
- Add refresh token endpoint
- Associated code cleanup
- Unit Test updates

### CODE REVIEW

File: src/main/java/dev/codesupport/web/common/service/controller/ErrorHandlerController.java [hunk 1]
```diff
@@ -138,6 +137,22 @@ Throwable getExceptionOrReturnNull(HttpServletRequest request) {
         return new RestResponse<>();
     }
 
+    @VisibleForTesting
+    HttpStatus updateHttpStatus(HttpStatus httpStatus, Throwable throwable) {
```
Comment (LamboCreeper) [inline src/main/java/dev/codesupport/web/common/service/controller/ErrorHandlerController.java:141]: Codacy found an issue: [Avoid reassigning parameters such as 'httpStatus'](https://app.codacy.com/gh/codesupport/website-backend/pullRequest?prid=5803379)

**Comment by LamboCreeper** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Issues
======
- Added 1
           

Complexity increasing per file
==============================
- src/main/java/dev/codesupport/web/common/security/access/evaluator/DiscordAccountLinkEvaluator.java  1
- src/test/java/dev/codesupport/testutils/builders/ShowcaseBuilder.java  3
- src/test/java/dev/codesupport/web/common/service/controller/AuthenticationControllerTest.java  2
- src/test/java/dev/codesupport/web/common/security/access/evaluator/ShowcaseCreateEvaluatorTest.java  1
- src/main/java/dev/codesupport/web/common/security/access/evaluator/ShowcaseCreateEvaluator.java  2
- src/test/java/dev/codesupport/web/common/security/access/evaluator/DiscordAccountLinkEvaluatorTest.java  1
- src/main/java/dev/codesupport/web/common/exception/ErrorControllerException.java  1
- src/test/java/dev/codesupport/web/common/security/AuthorizationServiceTest.java  1
- src/test/java/dev/codesupport/web/api/data/repository/UserRepositoryTest.java  1
- src/test/java/dev/codesupport/testutils/builders/CountryBuilder.java  1
- src/test/java/dev/codesupport/testutils/builders/RoleBuilder.java  2
- src/main/java/dev/codesupport/web/common/security/access/evaluator/TokenRefreshEvaluator.java  1
- src/test/java/dev/codesupport/testutils/builders/ContributorBuilder.java  3
- src/test/java/dev/codesupport/web/common/security/access/evaluator/TokenRefreshEvaluatorTest.java  1
- src/test/java/dev/codesupport/testutils/builders/ContributorListBuilder.java  2
- src/test/java/dev/codesupport/web/common/exception/ErrorControllerExceptionTest.java  1
- src/test/java/dev/codesupport/testutils/builders/UserAwardBuilder.java  1
- src/test/java/dev/codesupport/testutils/builders/PermissionBuilder.java  1
- src/main/java/dev/codesupport/web/common/security/AuthorizationServiceImpl.java  2
- src/test/java/dev/codesupport/testutils/builders/UserBuilder.java  4
         

Complexity decreasing per file
==============================
+ src/main/java/dev/codesupport/web/common/service/controller/ErrorHandlerController.java  -1
         

Clones added
============
- src/test/java/dev/codesupport/web/common/security/access/evaluator/ShowcaseCreateEvaluatorTest.java  6
- src/test/java/dev/codesupport/web/common/service/controller/ErrorHandlerControllerTest.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codesupport/website-backend/pullRequest?prid=5803379&bid=18997253)

**Comment by LamboCreeper** [comment]
Codacy Here is an overview of what got changed by this pull request:


```diff

Complexity increasing per file
==============================
- src/test/java/dev/codesupport/web/common/exception/ErrorControllerExceptionTest.java  1
- src/test/java/dev/codesupport/web/common/security/access/evaluator/DiscordAccountLinkEvaluatorTest.java  1
- src/test/java/dev/codesupport/web/common/security/AuthorizationServiceTest.java  1
- src/test/java/dev/codesupport/testutils/builders/UserBuilder.java  4
- src/main/java/dev/codesupport/web/common/security/access/evaluator/TokenRefreshEvaluator.java  1
- src/test/java/dev/codesupport/testutils/builders/UserAwardBuilder.java  1
- src/test/java/dev/codesupport/testutils/builders/ShowcaseBuilder.java  3
- src/main/java/dev/codesupport/web/common/exception/ErrorControllerException.java  1
- src/test/java/dev/codesupport/web/common/security/access/evaluator/ShowcaseCreateEvaluatorTest.java  1
- src/test/java/dev/codesupport/web/common/security/access/evaluator/TokenRefreshEvaluatorTest.java  1
- src/test/java/dev/codesupport/testutils/builders/ContributorBuilder.java  3
- src/test/java/dev/codesupport/web/common/service/controller/AuthenticationControllerTest.java  2
- src/test/java/dev/codesupport/web/api/data/repository/UserRepositoryTest.java  1
- src/main/java/dev/codesupport/web/common/security/access/evaluator/ShowcaseCreateEvaluator.java  2
- src/test/java/dev/codesupport/testutils/builders/ContributorListBuilder.java  2
- src/test/java/dev/codesupport/testutils/builders/RoleBuilder.java  2
- src/main/java/dev/codesupport/web/common/security/AuthorizationServiceImpl.java  2
- src/test/java/dev/codesupport/testutils/builders/CountryBuilder.java  1
- src/main/java/dev/codesupport/web/common/security/access/evaluator/DiscordAccountLinkEvaluator.java  1
- src/test/java/dev/codesupport/testutils/builders/PermissionBuilder.java  1
         

Complexity decreasing per file
==============================
+ src/main/java/dev/codesupport/web/common/service/controller/ErrorHandlerController.java  -1
         

Clones added
============
- src/test/java/dev/codesupport/web/common/security/access/evaluator/ShowcaseCreateEvaluatorTest.java  6
- src/test/java/dev/codesupport/web/common/service/controller/ErrorHandlerControllerTest.java  2
         
```


See the complete overview on [Codacy](https://app.codacy.com/gh/codesupport/website-backend/pullRequest?prid=5803379&bid=18997253)

**Review by LamboCreeper — APPROVED** [review]
